def encrypt(plaintext, key):
    encrypted_text = ""
    for i in range(len(plaintext)):
        encrypted_text += chr(ord(plaintext[i]) ^ ord(key[i % len(key)]))
    return encrypted_text

def decrypt(ciphertext, key):
    decrypted_text = ""
    for i in range(len(ciphertext)):
        decrypted_text += chr(ord(ciphertext[i]) ^ ord(key[i % len(key)]))
    return decrypted_text

plaintext = "ПРИКАЗ"
key = "ГАММА"

encrypted_text = encrypt(plaintext, key)
print("Зашифрованный текст:", encrypted_text)

decrypted_text = decrypt(encrypted_text, key)  # Используем decrypt, а не encrypt повторно
print("Расшифрованный текст:", decrypted_text)


import string

alphabet = "АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ"  # Заглавные буквы в правильном порядке

def encrypt_gamma(text, key_text):
    result = ""
    for i in range(len(text)):
        key_position = alphabet.index(key_text[i % len(key_text)]) + 1
        result_position = alphabet.index(text[i]) + key_position
        print(f"first {alphabet.index(text[i])} + second {key_position} = {result_position}")
        result += alphabet[result_position % 33]
    return result

# Тестируем функцию
print("\nГаммирование:")
encrypted = encrypt_gamma("ПРИКАЗ", "ГАММА")
print("Результат:", encrypted) 


